#ifndef SERIALCOMMANDS_H
#define SERIALCOMMANDS_H

#define GENERATE_ENUM( ENUM ) ENUM,
#define GENERATE_STRING( STRING ) #STRING,

#define FOREACH_SERIAL_COMMAND( SERIAL_COMMAND ) \
    SERIAL_COMMAND( INVALID )   \
    SERIAL_COMMAND( STATUS )  \
    SERIAL_COMMAND( BUFFERSIZE )   \
    SERIAL_COMMAND( SEPARATOR )  \
    SERIAL_COMMAND( PROGRAMCOUNT )   \
    SERIAL_COMMAND( PROGRAMINFO )  \
    SERIAL_COMMAND( ALLSTATUS )   \
    SERIAL_COMMAND( COLORS )  \
    SERIAL_COMMAND( VALUES )   \
    SERIAL_COMMAND( PIXELCOUNT )  \
    SERIAL_COMMAND( HARDWARE )   \
    SERIAL_COMMAND( VALUES_COLORS )  \
    SERIAL_COMMAND( COMMAND_COUNT )  \

enum SERIAL_COMMAND {
    FOREACH_SERIAL_COMMAND( GENERATE_ENUM )
};

static const char *SERIAL_COMMAND_STRING[] = {
    FOREACH_SERIAL_COMMAND( GENERATE_STRING )
};
#endif // SERIALCOMMANDS_H
